// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.DEB.Infrastructure.Persistence;

#nullable disable

namespace Nexus.DEB.Infrastructure.Migrations
{
    [DbContext(typeof(DebContext))]
    [Migration("20260116102351_AddVersionTitleToStandardVersionViews")]
    partial class AddVersionTitleToStandardVersionViews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus.DEB.Domain.Models.ChangeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeByUser")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("ChangeRecord", "common", t =>
                        {
                            t.HasTrigger("ChangeTracking");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.ChangeRecordItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChangeRecordId")
                        .HasColumnType("int");

                    b.Property<string>("ChangedFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FriendlyFieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ChangeRecordId");

                    b.ToTable("ChangeRecordItem", "common", t =>
                        {
                            t.HasTrigger("ChangeTracking")
                                .HasDatabaseName("ChangeTracking1");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short?>("CommentTypeId")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("CreatedByPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByPostTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByUserName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommentTypeId");

                    b.HasIndex("EntityId");

                    b.ToTable("Comments", "common");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.CommentDetail", b =>
                {
                    b.Property<string>("CreatedByFirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedByFirstName");

                    b.Property<string>("CreatedByLastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedByLastName");

                    b.Property<string>("CreatedByPost")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedByPostTitle");

                    b.Property<Guid>("CreatedByPostId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedByPostId");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedByUserName");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityId");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Text");

                    b.ToTable((string)null);

                    b.ToView("vw_CommentDetail", "common");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.CommentType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CommentType", "common");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Common.EntityHead", b =>
                {
                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityTypeTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<Guid>("LastModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnedByGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntityId");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("EntityTypeTitle");

                    b.HasIndex("LastModifiedDate");

                    b.HasIndex("OwnedById");

                    b.ToTable("EntityHead", "common", t =>
                        {
                            t.HasTrigger("EntityHead_ChangeTracking");
                        });

                    b
                        .UseTptMappingStrategy()
                        .HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.EntityHeadDetail", b =>
                {
                    b.Property<string>("CreatedByPostTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedByPostTitle");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityId");

                    b.Property<string>("EntityTypeTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EntityTypeTitle");

                    b.Property<string>("LastModifiedByPostTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LastModifiedByPostTitle");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModifiedDate");

                    b.Property<string>("OwnedByPostTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OwnedByPostTitle");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SerialNumber");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.ToTable((string)null);

                    b.ToView("vw_EntityHeadDetail", "common");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.MyWorkActivity", b =>
                {
                    b.Property<int>("ActivityID")
                        .HasColumnType("int")
                        .HasColumnName("ActivityID");

                    b.Property<string>("ActivityTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ActivityTitle");

                    b.Property<int>("FormCount")
                        .HasColumnType("int")
                        .HasColumnName("FormCount");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.MyWorkDetailItem", b =>
                {
                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DueDate");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityID");

                    b.Property<string>("EntityTypeTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EntityTypeTitle");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedDate");

                    b.Property<Guid>("ModuleID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ModuleID");

                    b.Property<string>("OwnerGroup")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OwnerGroup");

                    b.Property<string>("OwnerPost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OwnerPost");

                    b.Property<string>("PendingActivityList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PendingActivityList");

                    b.Property<string>("PendingActivityOwners")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PendingActivityOwners");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ReviewDate");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SerialNumber");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.Property<string>("TransferDates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TransferDates");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.MyWorkSummaryItem", b =>
                {
                    b.Property<string>("EntityTypeTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EntityTypeTitle");

                    b.Property<int>("FormCount")
                        .HasColumnType("int")
                        .HasColumnName("FormCount");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PostID");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostTitle");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Other.DashboardInfo", b =>
                {
                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedToPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EntityClosedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EntityOpenDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWorkflowActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ResponsibleOwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("ReviewDate")
                        .HasColumnType("date");

                    b.HasKey("EntityId");

                    b.ToTable("DashboardInfo", "common");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Other.ModuleInfo", b =>
                {
                    b.Property<Guid>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssemblyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("IOCName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsIssueLinkable")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SchemaName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ModuleId");

                    b.ToTable("ModuleInfo", (string)null);
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Other.ModuleSetting", b =>
                {
                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCustomerSet")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNullable")
                        .HasColumnType("bit");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModuleId", "Name");

                    b.HasIndex("TypeId");

                    b.ToTable("ModuleSetting", (string)null);
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Other.SettingsType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TypeId");

                    b.ToTable("SettingsType", (string)null);
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.PawsEntityDetail", b =>
                {
                    b.Property<int>("ActivityId")
                        .HasColumnType("int")
                        .HasColumnName("ActivityID");

                    b.Property<string>("ActivityTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ActivityTitle");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityID");

                    b.Property<int?>("PseudoStateId")
                        .HasColumnType("int")
                        .HasColumnName("PseudoStateID");

                    b.Property<string>("PseudoStateTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PseudoStateTitle");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<string>("StatusTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StatusTitle");

                    b.Property<int>("StepId")
                        .HasColumnType("int")
                        .HasColumnName("StepID");

                    b.ToTable((string)null);

                    b.ToView("vw_PawsEntityDetail", "common");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.PawsState", b =>
                {
                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityID");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StateTitle");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StateID");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProcessTemplateID");

                    b.ToTable((string)null);

                    b.ToView("vwPawsState", "common");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.RequirementCategory", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("RequirementCategory", "deb");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.RequirementExport", b =>
                {
                    b.Property<int?>("ComplianceWeighting")
                        .HasColumnType("int")
                        .HasColumnName("ComplianceWeighting");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<DateTime>("EffectiveEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EffectiveEndDate");

                    b.Property<DateTime>("EffectiveStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EffectiveStartDate");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityId");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModifiedDate");

                    b.Property<string>("RequirementCategoryTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RequirementCategoryTitle");

                    b.Property<string>("RequirementTypeTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RequirementTypeTitle");

                    b.Property<string>("SectionReferences")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SectionReferences");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SerialNumber");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.ToTable((string)null);

                    b.ToView("vw_RequirementExport", "deb");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.RequirementType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("RequirementType", "deb");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.SavedSearch", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("Context")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Filter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PostId", "Name", "Context");

                    b.ToTable("SavedSearch", "common");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.ScopeExport", b =>
                {
                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityId");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModifiedDate");

                    b.Property<int>("NumberOfLinkedStandardVersions")
                        .HasColumnType("int")
                        .HasColumnName("StandardVersionCount");

                    b.Property<string>("OwnedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OwnedBy");

                    b.Property<Guid>("OwnedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OwnedById");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SerialNumber");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("TargetImplementationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("TargetImplementationDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.ToTable((string)null);

                    b.ToView("vw_ScopeExport", "deb");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.ScopeSummary", b =>
                {
                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityId");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModifiedDate");

                    b.Property<int>("NumberOfLinkedStandardVersions")
                        .HasColumnType("int")
                        .HasColumnName("StandardVersionCount");

                    b.Property<string>("OwnedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OwnedBy");

                    b.Property<Guid>("OwnedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OwnedById");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.ToTable((string)null);

                    b.ToView("vw_ScopeSummary", "deb");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsReferenceDisplayed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTitleDisplayed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("StandardVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ParentSectionId");

                    b.HasIndex("StandardVersionId");

                    b.ToTable("Section", "deb");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.SectionRequirement", b =>
                {
                    b.Property<Guid>("SectionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequirementID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.HasKey("SectionID", "RequirementID");

                    b.HasIndex("RequirementID");

                    b.ToTable("SectionRequirement", "deb");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.SerialNumber", b =>
                {
                    b.Property<Guid>("SerialNumberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NextValue")
                        .HasColumnType("int");

                    b.HasKey("SerialNumberId");

                    b.HasIndex("ModuleId", "InstanceId", "EntityType");

                    b.ToTable("SerialNumber", (string)null);
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Standard", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Standard", "deb");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.StandardVersionDetailView", b =>
                {
                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedByPostTitle");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("Delimiter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Delimiter");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("EffectiveEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EffectiveEndDate");

                    b.Property<DateTime>("EffectiveStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EffectiveStartDate");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityId");

                    b.Property<string>("EntityTypeTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EntityTypeTitle");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LastModifiedByPostTitle");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModifiedDate");

                    b.Property<int>("MajorVersion")
                        .HasColumnType("int")
                        .HasColumnName("MajorVersion");

                    b.Property<int>("MinorVersion")
                        .HasColumnType("int")
                        .HasColumnName("MinorVersion");

                    b.Property<string>("OwnedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OwnedByPostTitle");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SerialNumber");

                    b.Property<short>("StandardId")
                        .HasColumnType("smallint")
                        .HasColumnName("StandardId");

                    b.Property<string>("StandardTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StandardTitle");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.ToTable((string)null);

                    b.ToView("vw_StandardVersionDetail", "deb");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.StandardVersionExport", b =>
                {
                    b.Property<string>("Delimiter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Delimiter");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("EffectiveEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EffectiveEndDate");

                    b.Property<DateTime>("EffectiveStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EffectiveStartDate");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityId");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModifiedDate");

                    b.Property<int?>("MajorVersion")
                        .HasColumnType("int");

                    b.Property<int?>("MinorVersion")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfLinkedScopes")
                        .HasColumnType("int")
                        .HasColumnName("ScopeCount");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SerialNumber");

                    b.Property<short>("StandardId")
                        .HasColumnType("smallint")
                        .HasColumnName("StandardId");

                    b.Property<string>("StandardTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StandardTitle");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StandardVersionTitle");

                    b.Property<string>("VersionTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VersionTitle");

                    b.ToTable((string)null);

                    b.ToView("vw_StandardVersionExport", "deb");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.StandardVersionSummary", b =>
                {
                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2")
                        .HasColumnName("EffectiveStartDate");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2")
                        .HasColumnName("EffectiveEndDate");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityId");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModifiedDate");

                    b.Property<int>("NumberOfLinkedScopes")
                        .HasColumnType("int")
                        .HasColumnName("ScopeCount");

                    b.Property<short>("StandardId")
                        .HasColumnType("smallint")
                        .HasColumnName("StandardId");

                    b.Property<string>("StandardTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StandardTitle");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StandardVersionTitle");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Version");

                    b.ToTable((string)null);

                    b.ToView("vw_StandardVersionSummary", "deb");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.StatementDetailView", b =>
                {
                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityId");

                    b.Property<string>("EntityTypeTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EntityTypeTitle");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnName("IsArchived");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnName("IsRemoved");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModifiedDate");

                    b.Property<string>("OwnedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OwnedBy");

                    b.Property<Guid>("OwnedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OwnedById");

                    b.Property<DateOnly?>("ReviewDate")
                        .HasColumnType("date")
                        .HasColumnName("ReviewDate");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SerialNumber");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.ToTable((string)null);

                    b.ToView("vw_StatementDetail", "deb");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.StatementExport", b =>
                {
                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityId");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModifiedDate");

                    b.Property<string>("OwnedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OwnedBy");

                    b.Property<Guid>("OwnedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OwnedById");

                    b.Property<string>("RequirementSerialNumbers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RequirementSerialNumbers");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SerialNumber");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.ToTable((string)null);

                    b.ToView("vw_StatementExport", "deb");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.StatementRequirementScope", b =>
                {
                    b.Property<Guid>("StatementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StatementId", "RequirementId", "ScopeId");

                    b.HasIndex("RequirementId");

                    b.HasIndex("ScopeId");

                    b.ToTable("StatementRequirementScope", "deb", t =>
                        {
                            t.HasTrigger("StatementRequirementScope_ChangeTracking");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.TaskDetailView", b =>
                {
                    b.Property<int?>("ActivityId")
                        .HasColumnType("int")
                        .HasColumnName("ActivityID");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("DueDate");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityId");

                    b.Property<string>("EntityTypeTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EntityTypeTitle");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnName("IsArchived");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnName("IsRemoved");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LastModifiedBy");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModifiedDate");

                    b.Property<string>("OwnedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OwnedBy");

                    b.Property<Guid>("OwnedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OwnedById");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SerialNumber");

                    b.Property<Guid>("StatementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StatementId");

                    b.Property<string>("StatementSerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StatementSerialNumber");

                    b.Property<string>("StatementTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StatementTitle");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TaskType");

                    b.Property<short>("TaskTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("TaskTypeId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.ToTable((string)null);

                    b.ToView("vw_TaskDetail", "deb");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.TaskExport", b =>
                {
                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DueDate");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityId");

                    b.Property<string>("OwnedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OwnedBy");

                    b.Property<Guid>("OwnedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OwnedById");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SerialNumber");

                    b.Property<Guid>("StatementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StatementId");

                    b.Property<string>("StatementSerialNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StatementSerialNumber");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<string>("TaskTypeTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TaskTypeTitle");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.ToTable((string)null);

                    b.ToView("vw_TaskExport", "deb");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.TaskSummary", b =>
                {
                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DueDate");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityId");

                    b.Property<string>("EntityTypeTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EntityTypeTitle");

                    b.Property<string>("OwnedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OwnedBy");

                    b.Property<Guid>("OwnedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("OwnedById");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SerialNumber");

                    b.Property<Guid>("StatementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StatementId");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<string>("TaskTypeTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TaskTypeTitle");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.ToTable((string)null);

                    b.ToView("vw_TaskSummary", "deb");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.TaskType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TaskType", "deb");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.UserAndPost", b =>
                {
                    b.Property<bool>("IsPostDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsPostDeleted");

                    b.Property<bool>("IsUserDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsUserDeleted");

                    b.Property<bool>("IsUserEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("IsUserEnabled");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("postID");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PostTitle");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userID");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserName");

                    b.ToTable((string)null);

                    b.ToView("XDB_CIS_User_Post", "common");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.ViewPost", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int>("PostTypeId")
                        .HasColumnType("int")
                        .HasColumnName("PostTypeID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.ToTable((string)null);

                    b.ToView("XDB_CIS_View_Post", "common");
                });

            modelBuilder.Entity("ScopeRequirement", b =>
                {
                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RequirementId", "ScopeId");

                    b.HasIndex("ScopeId");

                    b.ToTable("ScopeRequirement", "deb");
                });

            modelBuilder.Entity("StandardVersionRequirement", b =>
                {
                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StandardVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RequirementId", "StandardVersionId");

                    b.HasIndex("StandardVersionId");

                    b.ToTable("StandardVersionRequirement", "deb");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Requirement", b =>
                {
                    b.HasBaseType("Nexus.DEB.Domain.Models.Common.EntityHead");

                    b.Property<int?>("ComplianceWeighting")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveStartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsReferenceDisplayed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTitleDisplayed")
                        .HasColumnType("bit");

                    b.Property<short>("RequirementCategoryId")
                        .HasColumnType("smallint");

                    b.Property<short>("RequirementTypeId")
                        .HasColumnType("smallint");

                    b.HasIndex("RequirementCategoryId");

                    b.HasIndex("RequirementTypeId");

                    b.ToTable("Requirement", "deb");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Scope", b =>
                {
                    b.HasBaseType("Nexus.DEB.Domain.Models.Common.EntityHead");

                    b.Property<DateTime?>("TargetImplementationDate")
                        .HasColumnType("datetime2");

                    b.ToTable("Scope", "deb");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.StandardVersion", b =>
                {
                    b.HasBaseType("Nexus.DEB.Domain.Models.Common.EntityHead");

                    b.Property<string>("Delimiter")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValue("");

                    b.Property<DateTime?>("EffectiveEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MajorVersion")
                        .HasColumnType("int");

                    b.Property<int?>("MinorVersion")
                        .HasColumnType("int");

                    b.Property<short>("StandardId")
                        .HasColumnType("smallint");

                    b.Property<string>("VersionTitle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("");

                    b.HasIndex("StandardId");

                    b.ToTable("StandardVersion", "deb");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Statement", b =>
                {
                    b.HasBaseType("Nexus.DEB.Domain.Models.Common.EntityHead");

                    b.Property<DateOnly?>("ReviewDate")
                        .HasColumnType("date");

                    b.ToTable("Statement", "deb", t =>
                        {
                            t.HasTrigger("Statement_ChangeTracking");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Task", b =>
                {
                    b.HasBaseType("Nexus.DEB.Domain.Models.Common.EntityHead");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid>("StatementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("TaskTypeId")
                        .HasColumnType("smallint");

                    b.HasIndex("StatementId");

                    b.HasIndex("TaskTypeId");

                    b.ToTable("Task", "deb", t =>
                        {
                            t.HasTrigger("Task_ChangeTracking");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.ChangeRecordItem", b =>
                {
                    b.HasOne("Nexus.DEB.Domain.Models.ChangeRecord", "ChangeRecord")
                        .WithMany("ChangeRecordItems")
                        .HasForeignKey("ChangeRecordId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChangeRecord");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Comment", b =>
                {
                    b.HasOne("Nexus.DEB.Domain.Models.CommentType", "CommentType")
                        .WithMany()
                        .HasForeignKey("CommentTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CommentType");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Other.ModuleSetting", b =>
                {
                    b.HasOne("Nexus.DEB.Domain.Models.Other.ModuleInfo", "ModuleInfo")
                        .WithMany("ModuleSettings")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.DEB.Domain.Models.Other.SettingsType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ModuleInfo");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Section", b =>
                {
                    b.HasOne("Nexus.DEB.Domain.Models.Section", "ParentSection")
                        .WithMany("ChildSections")
                        .HasForeignKey("ParentSectionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Nexus.DEB.Domain.Models.StandardVersion", "StandardVersion")
                        .WithMany()
                        .HasForeignKey("StandardVersionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentSection");

                    b.Navigation("StandardVersion");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.SectionRequirement", b =>
                {
                    b.HasOne("Nexus.DEB.Domain.Models.Requirement", "Requirement")
                        .WithMany("SectionRequirements")
                        .HasForeignKey("RequirementID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Nexus.DEB.Domain.Models.Section", "Section")
                        .WithMany("SectionRequirements")
                        .HasForeignKey("SectionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Requirement");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.StatementRequirementScope", b =>
                {
                    b.HasOne("Nexus.DEB.Domain.Models.Requirement", "Requirement")
                        .WithMany("StatementsRequirementsScopes")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Nexus.DEB.Domain.Models.Scope", "Scope")
                        .WithMany("StatementsRequirementsScopes")
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Nexus.DEB.Domain.Models.Statement", "Statement")
                        .WithMany("StatementsRequirementsScopes")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Requirement");

                    b.Navigation("Scope");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("ScopeRequirement", b =>
                {
                    b.HasOne("Nexus.DEB.Domain.Models.Requirement", null)
                        .WithMany()
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Nexus.DEB.Domain.Models.Scope", null)
                        .WithMany()
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("StandardVersionRequirement", b =>
                {
                    b.HasOne("Nexus.DEB.Domain.Models.Requirement", null)
                        .WithMany()
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Nexus.DEB.Domain.Models.StandardVersion", null)
                        .WithMany()
                        .HasForeignKey("StandardVersionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Requirement", b =>
                {
                    b.HasOne("Nexus.DEB.Domain.Models.Common.EntityHead", null)
                        .WithOne()
                        .HasForeignKey("Nexus.DEB.Domain.Models.Requirement", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.DEB.Domain.Models.RequirementCategory", "RequirementCategory")
                        .WithMany()
                        .HasForeignKey("RequirementCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Nexus.DEB.Domain.Models.RequirementType", "RequirementType")
                        .WithMany()
                        .HasForeignKey("RequirementTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RequirementCategory");

                    b.Navigation("RequirementType");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Scope", b =>
                {
                    b.HasOne("Nexus.DEB.Domain.Models.Common.EntityHead", null)
                        .WithOne()
                        .HasForeignKey("Nexus.DEB.Domain.Models.Scope", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.StandardVersion", b =>
                {
                    b.HasOne("Nexus.DEB.Domain.Models.Common.EntityHead", null)
                        .WithOne()
                        .HasForeignKey("Nexus.DEB.Domain.Models.StandardVersion", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.DEB.Domain.Models.Standard", "Standard")
                        .WithMany()
                        .HasForeignKey("StandardId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Standard");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Statement", b =>
                {
                    b.HasOne("Nexus.DEB.Domain.Models.Common.EntityHead", null)
                        .WithOne()
                        .HasForeignKey("Nexus.DEB.Domain.Models.Statement", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Task", b =>
                {
                    b.HasOne("Nexus.DEB.Domain.Models.Common.EntityHead", null)
                        .WithOne()
                        .HasForeignKey("Nexus.DEB.Domain.Models.Task", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.DEB.Domain.Models.Statement", "Statement")
                        .WithMany("Tasks")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Nexus.DEB.Domain.Models.TaskType", "TaskType")
                        .WithMany()
                        .HasForeignKey("TaskTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Statement");

                    b.Navigation("TaskType");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.ChangeRecord", b =>
                {
                    b.Navigation("ChangeRecordItems");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Other.ModuleInfo", b =>
                {
                    b.Navigation("ModuleSettings");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Section", b =>
                {
                    b.Navigation("ChildSections");

                    b.Navigation("SectionRequirements");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Requirement", b =>
                {
                    b.Navigation("SectionRequirements");

                    b.Navigation("StatementsRequirementsScopes");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Scope", b =>
                {
                    b.Navigation("StatementsRequirementsScopes");
                });

            modelBuilder.Entity("Nexus.DEB.Domain.Models.Statement", b =>
                {
                    b.Navigation("StatementsRequirementsScopes");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
